name: CI
on:
  push:
    branches:
      - main
  pull_request:
  merge_group:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  change-detection:
    name: ðŸ” Change
    uses: munich-quantum-toolkit/workflows/.github/workflows/reusable-change-detection.yml@56cf3608b07dc10bda5b98d77ed6ad21ecf7ef5d # v1.17.0

  cpp-tests-ubuntu:
    name: ðŸ‡¨â€Œ Test ðŸ§
    needs: change-detection
    if: fromJSON(needs.change-detection.outputs.run-cpp-tests) && !contains(github.event.pull_request.labels.*.name, 'extensive-cpp-ci')
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-24.04, ubuntu-24.04-arm]
        compiler: [gcc]
        config: [Release]
        include:
          - runs-on: ubuntu-24.04
            compiler: gcc
            config: Debug
    uses: munich-quantum-toolkit/workflows/.github/workflows/reusable-cpp-tests-ubuntu.yml@56cf3608b07dc10bda5b98d77ed6ad21ecf7ef5d # v1.17.0
    with:
      runs-on: ${{ matrix.runs-on }}
      compiler: ${{ matrix.compiler }}
      config: ${{ matrix.config }}
      setup-z3: true

  cpp-tests-macos:
    name: ðŸ‡¨â€Œ Test ðŸŽ
    needs: change-detection
    if: fromJSON(needs.change-detection.outputs.run-cpp-tests) && !contains(github.event.pull_request.labels.*.name, 'extensive-cpp-ci')
    strategy:
      fail-fast: false
      matrix:
        runs-on: [macos-14]
        compiler: [clang]
        config: [Release, Debug]
    uses: munich-quantum-toolkit/workflows/.github/workflows/reusable-cpp-tests-macos.yml@56cf3608b07dc10bda5b98d77ed6ad21ecf7ef5d # v1.17.0
    with:
      runs-on: ${{ matrix.runs-on }}
      compiler: ${{ matrix.compiler }}
      config: ${{ matrix.config }}
      cmake-args: -DMQT_CORE_WITH_GMP=ON
      setup-z3: true

  cpp-tests-windows:
    name: ðŸ‡¨â€Œ Test ðŸ
    needs: change-detection
    if: fromJSON(needs.change-detection.outputs.run-cpp-tests) && !contains(github.event.pull_request.labels.*.name, 'extensive-cpp-ci')
    strategy:
      fail-fast: false
      matrix:
        runs-on: [windows-2022, windows-11-arm]
        compiler: [msvc]
        config: [Release]
        include:
          - runs-on: windows-2022
            compiler: msvc
            config: Debug
    uses: munich-quantum-toolkit/workflows/.github/workflows/reusable-cpp-tests-windows.yml@56cf3608b07dc10bda5b98d77ed6ad21ecf7ef5d # v1.17.0
    with:
      runs-on: ${{ matrix.runs-on }}
      compiler: ${{ matrix.compiler }}
      config: ${{ matrix.config }}
      setup-z3: true

  # run extensive C++ tests on PRs labeled with the `extensive-cpp-ci` label
  cpp-tests-extensive-ubuntu:
    name: ðŸ‡¨â€Œ Test (Extensive) ðŸ§
    needs: change-detection
    if: fromJSON(needs.change-detection.outputs.run-cpp-tests) && github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'extensive-cpp-ci')
    strategy:
      fail-fast: false
      matrix:
        runs-on:
          [ubuntu-22.04, ubuntu-24.04, ubuntu-22.04-arm, ubuntu-24.04-arm]
        compiler: [gcc, clang, clang-19, clang-20]
        config: [Release, Debug]
        exclude:
          # both combinations do not support C++20 due to the compiler being too old
          - runs-on: ubuntu-22.04
            compiler: clang
          - runs-on: ubuntu-22.04-arm
            compiler: clang
    uses: munich-quantum-toolkit/workflows/.github/workflows/reusable-cpp-tests-ubuntu.yml@56cf3608b07dc10bda5b98d77ed6ad21ecf7ef5d # v1.17.0
    with:
      runs-on: ${{ matrix.runs-on }}
      compiler: ${{ matrix.compiler }}
      config: ${{ matrix.config }}
      setup-z3: true

  # run extensive C++ tests on PRs labeled with the `extensive-cpp-ci` label
  cpp-tests-extensive-macos:
    name: ðŸ‡¨â€Œ Test (Extensive) ðŸŽ
    needs: change-detection
    if: fromJSON(needs.change-detection.outputs.run-cpp-tests) && github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'extensive-cpp-ci')
    strategy:
      fail-fast: false
      matrix:
        runs-on: [macos-14, macos-15]
        compiler: [clang, clang-19, clang-20, gcc-14, gcc-15]
        config: [Release, Debug]
        exclude:
          # see https://github.com/munich-quantum-toolkit/core/issues/979
          - runs-on: macos-15
            compiler: gcc-14
          - runs-on: macos-15
            compiler: gcc-15
    uses: munich-quantum-toolkit/workflows/.github/workflows/reusable-cpp-tests-macos.yml@56cf3608b07dc10bda5b98d77ed6ad21ecf7ef5d # v1.17.0
    with:
      runs-on: ${{ matrix.runs-on }}
      compiler: ${{ matrix.compiler }}
      config: ${{ matrix.config }}
      cmake-args: -DMQT_CORE_WITH_GMP=ON
      setup-z3: true

  # run extensive C++ tests on PRs labeled with the `extensive-cpp-ci` label
  cpp-tests-extensive-windows:
    name: ðŸ‡¨â€Œ Test (Extensive) ðŸ
    needs: change-detection
    if: fromJSON(needs.change-detection.outputs.run-cpp-tests) && github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'extensive-cpp-ci')
    strategy:
      fail-fast: false
      matrix:
        runs-on: [windows-2022, windows-2025, windows-11-arm]
        compiler: [msvc, clang]
        config: [Release, Debug]
    uses: munich-quantum-toolkit/workflows/.github/workflows/reusable-cpp-tests-windows.yml@56cf3608b07dc10bda5b98d77ed6ad21ecf7ef5d # v1.17.0
    with:
      runs-on: ${{ matrix.runs-on }}
      compiler: ${{ matrix.compiler }}
      config: ${{ matrix.config }}
      setup-z3: true

  cpp-coverage:
    name: ðŸ‡¨â€Œ Coverage
    needs: change-detection
    if: fromJSON(needs.change-detection.outputs.run-cpp-tests)
    uses: munich-quantum-toolkit/workflows/.github/workflows/reusable-cpp-coverage.yml@56cf3608b07dc10bda5b98d77ed6ad21ecf7ef5d # v1.17.0
    with:
      setup-z3: true
    permissions:
      contents: read
      id-token: write

  # to properly link python bindings, the target must be enabled and pybind11 must be installed
  cpp-linter:
    name: ðŸ‡¨â€Œ Lint
    needs: change-detection
    if: fromJSON(needs.change-detection.outputs.run-cpp-linter)
    uses: munich-quantum-toolkit/workflows/.github/workflows/reusable-cpp-linter.yml@56cf3608b07dc10bda5b98d77ed6ad21ecf7ef5d # v1.17.0
    with:
      clang-version: 20
      cmake-args: -DBUILD_MQT_QMAP_BINDINGS=ON
      files-changed-only: true
      install-pkgs: "pybind11==3.0.0"
      setup-python: true
      setup-z3: true
      cpp-linter-extra-args: "-std=c++20"

  python-tests:
    name: ðŸ Test
    needs: change-detection
    if: fromJSON(needs.change-detection.outputs.run-python-tests)
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-24.04, ubuntu-24.04-arm, macos-14, windows-2022]
    uses: munich-quantum-toolkit/workflows/.github/workflows/reusable-python-tests.yml@56cf3608b07dc10bda5b98d77ed6ad21ecf7ef5d # v1.17.0
    with:
      runs-on: ${{ matrix.runs-on }}
      setup-z3: true

  python-coverage:
    name: ðŸ Coverage
    needs: [change-detection, python-tests]
    if: fromJSON(needs.change-detection.outputs.run-python-tests)
    uses: munich-quantum-toolkit/workflows/.github/workflows/reusable-python-coverage.yml@56cf3608b07dc10bda5b98d77ed6ad21ecf7ef5d # v1.17.0
    permissions:
      contents: read
      id-token: write

  # run extensive Python tests on PRs labeled with the `extensive-python-ci` label
  python-tests-extensive:
    name: ðŸ Test (Extensive)
    needs: change-detection
    if: fromJSON(needs.change-detection.outputs.run-python-tests) && github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'extensive-python-ci')
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-22.04, ubuntu-22.04-arm, macos-15, windows-2025]
        exclude:
          # see https://github.com/munich-quantum-toolkit/qmap/issues/703
          - runs-on: macos-15
    uses: munich-quantum-toolkit/workflows/.github/workflows/reusable-python-tests.yml@56cf3608b07dc10bda5b98d77ed6ad21ecf7ef5d # v1.17.0
    with:
      runs-on: ${{ matrix.runs-on }}
      setup-z3: true

  python-linter:
    name: ðŸ Lint
    needs: change-detection
    if: fromJSON(needs.change-detection.outputs.run-python-tests)
    uses: munich-quantum-toolkit/workflows/.github/workflows/reusable-python-linter.yml@56cf3608b07dc10bda5b98d77ed6ad21ecf7ef5d # v1.17.0
    with:
      setup-z3: true

  build-sdist:
    name: ðŸš€ CD
    needs: change-detection
    if: fromJSON(needs.change-detection.outputs.run-cd)
    uses: munich-quantum-toolkit/workflows/.github/workflows/reusable-python-packaging-sdist.yml@56cf3608b07dc10bda5b98d77ed6ad21ecf7ef5d # v1.17.0

  build-wheel:
    name: ðŸš€ CD
    needs: change-detection
    if: fromJSON(needs.change-detection.outputs.run-cd)
    strategy:
      fail-fast: false
      matrix:
        runs-on:
          [
            ubuntu-24.04,
            ubuntu-24.04-arm,
            macos-14,
            windows-2022,
            windows-11-arm,
          ]
    uses: munich-quantum-toolkit/workflows/.github/workflows/reusable-python-packaging-wheel-cibuildwheel.yml@56cf3608b07dc10bda5b98d77ed6ad21ecf7ef5d # v1.17.0
    with:
      runs-on: ${{ matrix.runs-on }}
      setup-z3: true
      # 4.13.0 has incorrectly tagged manylinux wheels
      z3-version: 4.12.6

  # this job does nothing and is only used for branch protection
  required-checks-pass:
    name: ðŸš¦ Check
    if: always()
    needs:
      - change-detection
      - cpp-tests-ubuntu
      - cpp-tests-macos
      - cpp-tests-windows
      - cpp-tests-extensive-ubuntu
      - cpp-tests-extensive-macos
      - cpp-tests-extensive-windows
      - cpp-coverage
      - cpp-linter
      - python-tests
      - python-linter
      - python-tests-extensive
      - build-sdist
      - build-wheel
    runs-on: ubuntu-latest
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@05ac9388f0aebcb5727afa17fcccfecd6f8ec5fe # v1.2.2
        with:
          allowed-skips: >-
            ${{
              fromJSON(needs.change-detection.outputs.run-cpp-tests) && !contains(github.event.pull_request.labels.*.name, 'extensive-cpp-ci')
              && '' || 'cpp-tests-ubuntu,cpp-tests-macos,cpp-tests-windows,'
            }}
            ${{
              fromJSON(needs.change-detection.outputs.run-cpp-tests) && github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'extensive-cpp-ci')
              && '' || 'cpp-tests-extensive-ubuntu,cpp-tests-extensive-macos,cpp-tests-extensive-windows,'
            }}
            ${{
              fromJSON(needs.change-detection.outputs.run-cpp-tests)
              && '' || 'cpp-coverage,'
            }}
            ${{
              fromJSON(needs.change-detection.outputs.run-cpp-linter)
              && '' || 'cpp-linter,'
            }}
            ${{
              fromJSON(needs.change-detection.outputs.run-python-tests)
              && '' || 'python-tests,python-coverage,'
            }}
            ${{
              fromJSON(needs.change-detection.outputs.run-python-tests) && github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'extensive-python-ci')
              && '' || 'python-tests-extensive,'
            }}
            ${{
              fromJSON(needs.change-detection.outputs.run-python-tests)
              && '' || 'python-linter,'
            }}
            ${{
              fromJSON(needs.change-detection.outputs.run-cd)
              && '' || 'build-sdist,build-wheel'
            }}
          jobs: ${{ toJSON(needs) }}
