name: Templating
on:
  pull_request:
    paths:
      - ".github/workflows/templating.yml"
  workflow_dispatch: # Allow manual triggering

jobs:
  render-template:
    name: Render template
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - id: create-token
        uses: actions/create-github-app-token@67018539274d69449ef7c02e8e71183d1719ab42 # v2.1.4
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - uses: munich-quantum-toolkit/templates@842d18d2fae61d82de309cc3b78a45e13be042d6 # v1.1.7
        with:
          token: ${{ steps.create-token.outputs.token }}
          name: QMAP
          organization: ${{ github.repository_owner }}
          project-type: c++-python
          repository: ${{ github.event.repository.name }}
